[workspace]
members = [
    "struum_network",
    "struum_opengl",
    "struum_types",
]
resolver="3"

[package]
name = "struum-net"
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
struum_opengl = {path = "./struum_opengl"}
struum_types = {path = "./struum_types"}
struum_network = {path = "./struum_network"}

[dependencies]
struum_opengl = { workspace = true }
struum_types = { workspace = true }
struum_network = { workspace = true }
